const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const outputDir = path.resolve(process.env.BACKUP_DIR || path.join(__dirname, '..', 'backups'));
const key = process.env.BACKUP_ENCRYPTION_KEY;
if (!process.env.DATABASE_URL || !key || Buffer.from(key, 'base64').length !== 32) throw new Error('DATABASE_URL and a base64 32-byte BACKUP_ENCRYPTION_KEY are required');
fs.mkdirSync(outputDir, { recursive: true, mode: 0o700 });
const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const destination = path.join(outputDir, `banglasketch-${stamp}.dump.enc`);
const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', Buffer.from(key, 'base64'), iv);
const output = fs.createWriteStream(destination, { mode: 0o600 }); output.write(iv);
const dump = spawn('pg_dump', ['--format=custom', '--no-owner', process.env.DATABASE_URL], { stdio: ['ignore','pipe','inherit'] });
cipher.pipe(output, { end: false }); dump.stdout.pipe(cipher);
dump.on('close', code => { if (code) return output.destroy(new Error('pg_dump failed')); });
cipher.on('end', () => output.end(cipher.getAuthTag()));
output.on('close', () => { if (!process.exitCode) console.log(destination); });
