# Generated by Django 5.2.17 on 2026-09-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCredential',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('password_hash', models.TextField()),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Legacy Admin Credential',
                'verbose_name_plural': 'Legacy Admin Credentials',
                'db_table': 'admin_credentials',
            },
        ),
        migrations.CreateModel(
            name='AdminPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('otp_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.CharField(default='unknown', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'db_table': 'admin_password_resets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('token_version', models.IntegerField(default=1)),
                ('totp_secret', models.TextField(blank=True, null=True)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('pending_totp_secret', models.TextField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'db_table': 'admin_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField()),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, db_column='admin_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_records', to='authentication.adminuser')),
            ],
            options={
                'verbose_name': 'Login History Record',
                'verbose_name_plural': 'Login History',
                'db_table': 'login_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
