# Generated by Django 5.2.17 on 2026-09-10 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('featured_image', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('author', models.CharField(default='Banglasketch Team', max_length=255)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_publish_date', models.DateTimeField(blank=True, null=True)),
                ('reading_time', models.IntegerField(default=5)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('cloudinary_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blog_posts',
                'ordering': ['-published_date', '-id'],
            },
        ),
    ]
