# Generated by Django 5.2.17 on 2026-09-20 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=80, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.adminuser')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.invoice')),
            ],
            options={
                'db_table': 'invoice_revisions',
                'constraints': [models.UniqueConstraint(fields=('invoice', 'revision'), name='unique_invoice_revision')],
            },
        ),
    ]
