# Generated by Django 5.2.17 on 2026-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=160, null=True)),
                ('location', models.CharField(max_length=255)),
                ('space_size', models.CharField(blank=True, max_length=120, null=True)),
                ('project_note', models.TextField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('10:00', '10:00 AM'), ('12:00', '12:00 PM'), ('15:00', '3:00 PM'), ('17:00', '5:00 PM')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Visit Booking',
                'verbose_name_plural': 'Site Visit Bookings',
                'db_table': 'site_visit_bookings',
                'ordering': ['visit_date', 'time_slot', '-submitted_at'],
                'indexes': [models.Index(fields=['visit_date', 'time_slot', 'status'], name='site_visit__visit_d_59ec40_idx'), models.Index(fields=['status', 'submitted_at'], name='site_visit__status_f744d6_idx')],
            },
        ),
    ]
