# Generated by Django 5.2.17 on 2026-09-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_sitevisitbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_visit_blocked_dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisitTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=5, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'site_visit_time_slots',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.AlterField(
            model_name='sitevisitbooking',
            name='time_slot',
            field=models.CharField(max_length=5),
        ),
    ]
