# Generated by Django 5.2.17 on 2026-09-12 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_sitevisitblockeddate_sitevisittimeslot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactemailjob',
            unique_together={('submission', 'kind')},
        ),
        migrations.AddField(
            model_name='contactemailjob',
            name='site_visit_booking',
            field=models.ForeignKey(blank=True, db_column='site_visit_booking_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_jobs', to='leads.sitevisitbooking'),
        ),
        migrations.AddField(
            model_name='sitevisitbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitbooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitbooking',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactemailjob',
            name='kind',
            field=models.CharField(choices=[('notification', 'Notification'), ('confirmation', 'Confirmation'), ('site_visit_notification', 'Site Visit Notification'), ('site_visit_confirmation', 'Site Visit Confirmation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactemailjob',
            name='submission',
            field=models.ForeignKey(blank=True, db_column='submission_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_jobs', to='leads.contactsubmission'),
        ),
        migrations.AlterUniqueTogether(
            name='contactemailjob',
            unique_together={('site_visit_booking', 'kind'), ('submission', 'kind')},
        ),
    ]
