# Generated by Django 5.2.17 on 2026-09-15 13:15

from django.db import migrations, models


def check_existing_records(apps, schema_editor):
    alias = schema_editor.connection.alias
    bookings = apps.get_model("leads", "SiteVisitBooking").objects.using(alias)
    duplicates = (bookings.filter(deleted_at__isnull=True).exclude(status="cancelled")
                  .values("visit_date", "time_slot").annotate(total=models.Count("pk"))
                  .filter(total__gt=1).exists())
    jobs = apps.get_model("leads", "ContactEmailJob").objects.using(alias)
    valid_targets = (
        models.Q(submission__isnull=False, site_visit_booking__isnull=True,
                 kind__in=["notification", "confirmation"])
        | models.Q(submission__isnull=True, site_visit_booking__isnull=False,
                   kind__in=["site_visit_notification", "site_visit_confirmation"])
    )
    if duplicates or jobs.exclude(valid_targets).exists():
        raise RuntimeError(
            "Resolve duplicate active site-visit slots and invalid email-job targets before "
            "applying leads.0006. No existing records have been deleted."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_update_email_job_kind_constraint'),
    ]

    operations = [
        migrations.RunPython(check_existing_records, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='contactemailjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['notification', 'confirmation']), ('site_visit_booking__isnull', True), ('submission__isnull', False)), models.Q(('kind__in', ['site_visit_notification', 'site_visit_confirmation']), ('site_visit_booking__isnull', False), ('submission__isnull', True)), _connector='OR'), name='email_job_target_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='sitevisitbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('status', 'cancelled'), _negated=True)), fields=('visit_date', 'time_slot'), name='unique_reserved_site_visit_slot'),
        ),
    ]
