# Generated by Django 5.2.17 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_match_legacy_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['published', 'deleted_at', 'category'], name='proj_pub_del_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['published', 'deleted_at', 'featured'], name='proj_pub_del_feat_idx'),
        ),
    ]
