# Generated by Django 5.2.17 on 2026-09-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('alternate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('portal_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(default='consultation', max_length=50)),
                ('current_milestone', models.TextField(blank=True, null=True)),
                ('next_milestone', models.TextField(blank=True, null=True)),
                ('agreed_scope', models.TextField(blank=True, null=True)),
                ('agreed_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='clients.client')),
                ('project_manager', models.ForeignKey(blank=True, db_column='project_manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='authentication.adminuser')),
            ],
            options={
                'verbose_name': 'Client Project',
                'verbose_name_plural': 'Client Projects',
                'db_table': 'client_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('proposed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('timeline_impact_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=50)),
                ('client_notes', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_change_orders', to='authentication.adminuser')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='clients.clientproject')),
            ],
            options={
                'verbose_name': 'Change Order',
                'verbose_name_plural': 'Change Orders',
                'db_table': 'change_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('project_location', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=50)),
                ('service_scope', models.CharField(max_length=50)),
                ('approx_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new_enquiry', 'New Enquiry'), ('contacted', 'Contacted'), ('consultation', 'Consultation'), ('site_visit', 'Site Visit'), ('proposal_sent', 'Proposal Sent'), ('approved', 'Approved'), ('active_project', 'Active Project'), ('handover', 'Handover'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='new_enquiry', max_length=50)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True, null=True)),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enquiries', to='authentication.adminuser')),
                ('client', models.ForeignKey(blank=True, db_column='client_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='clients.client')),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'db_table': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientproject',
            name='enquiry',
            field=models.ForeignKey(blank=True, db_column='enquiry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to='clients.enquiry'),
        ),
        migrations.CreateModel(
            name='EnquiryFollowUp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(default='call', max_length=50)),
                ('summary', models.TextField()),
                ('next_action', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_follow_ups', to='authentication.adminuser')),
                ('enquiry', models.ForeignKey(db_column='enquiry_id', on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='clients.enquiry')),
            ],
            options={
                'verbose_name': 'Enquiry Follow-Up',
                'verbose_name_plural': 'Enquiry Follow-Ups',
                'db_table': 'enquiry_follow_ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=50)),
                ('approved_version', models.IntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='clients.clientproject')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('scope_summary', models.TextField()),
                ('proposed_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('timeline_days', models.IntegerField(blank=True, null=True)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_versions_authored', to='authentication.adminuser')),
                ('proposal', models.ForeignKey(db_column='proposal_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clients.proposal')),
            ],
            options={
                'db_table': 'proposal_versions',
                'ordering': ['-version'],
                'unique_together': {('proposal', 'version')},
            },
        ),
    ]
