export const NEW_BLOG_POSTS = [
  {
    id: "kitchen-renovations-tradition-modernity-dhaka",
    title: "Kitchen Renovations That Blend Tradition with Modernity",
    slug: "kitchen-renovations-tradition-modernity-dhaka",
    excerpt:
      "Discover how Dhaka homeowners are reimagining their kitchens by merging timeless Bangladeshi culinary traditions with sleek modern designs. From open shelving that celebrates brass utensils to smart storage solutions for small Dhaka apartments, these renovations tell a story of heritage and innovation.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    category: "Kitchen Renovations",
    publishedDate: "2026-09-04",
    author: "Banglasketch Team",
    readingTime: 6,
    featured: true,
    instagramCaption: "Where birista meets breakfast counter 🏠✨ Where Dhaka's kitchens tell stories of home.",
    metaDescription:
      "Explore kitchen renovation ideas blending Bangladeshi tradition with modern design. Expert interior design services in Dhaka for functional, beautiful kitchens.",
  },
  {
    id: "modern-bedroom-design-sanctuaries-dhaka",
    title: "Modern Bedroom Design: Creating Sanctuaries in Dhaka Homes",
    slug: "modern-bedroom-design-sanctuaries-dhaka",
    excerpt:
      "Your bedroom should be a retreat from Dhaka's bustling streets. We explore how thoughtful design can transform even the smallest bedroom into a luxurious sanctuary. Learn about space-maximizing wardrobes, calming color palettes inspired by Bengal sunsets, and the art of bedroom lighting.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80",
    category: "Modern Bedroom Design",
    publishedDate: "2026-09-03",
    author: "Banglasketch Team",
    readingTime: 7,
    featured: true,
    instagramCaption: "Escape the city chaos in your own sanctuary 🛏️ Dhaka's most peaceful rooms start with vision.",
    metaDescription:
      "Transform your Dhaka bedroom into a peaceful sanctuary with modern design ideas. Expert bedroom interior design tips for urban Bangladeshi homes.",
  },
  {
    id: "small-space-solutions-dhaka-apartments",
    title: "Small Space Solutions: Maximizing Dhaka Apartments",
    slug: "small-space-solutions-dhaka-apartments",
    excerpt:
      "Living large in Gulshan doesn't require a Gulshan-sized budget. This guide reveals how Dhaka's top designers are conquering spatial challenges with multifunctional furniture, vertical storage hacks, and clever room dividers that make 800 sq ft feel like 1200.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80",
    category: "Small Space Solutions",
    publishedDate: "2026-09-02",
    author: "Banglasketch Team",
    readingTime: 6,
    featured: true,
    instagramCaption: "Big ideas for Dhaka's coziest corners 📐 Small footprint, grand style.",
    metaDescription:
      "Maximize your small Dhaka apartment with expert interior design solutions. Clever space-saving ideas for Gulshan, Banani, and all Bangladesh urban homes.",
  },
  {
    id: "sustainable-eco-friendly-interiors-dhaka",
    title: "Sustainable Interiors: Eco-Friendly Design for Dhaka Homes",
    slug: "sustainable-eco-friendly-interiors-dhaka",
    excerpt:
      "Go green without compromising on elegance. From reclaimed teak furniture sourced from Sylhet workshops to natural lime wash paints that breathe with your walls, discover how sustainable choices can define Dhaka's luxury interiors while honoring Bangladesh's environmental commitments.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    category: "Sustainable/Eco-Friendly Interiors",
    publishedDate: "2026-08-30",
    author: "Banglasketch Team",
    readingTime: 5,
    featured: false,
    instagramCaption: "Luxury that loves the planet 🌍 Sustainable Dhaka homes designed with heart.",
    metaDescription:
      "Eco-friendly interior design solutions for Dhaka homes. Sustainable materials and green design ideas from Bangladesh's leading interior firm.",
  },
  {
    id: "budget-friendly-makeovers-dhaka",
    title: "Budget-Friendly Makeovers: Dhaka Homes Transformed Under BDT 5 Lakh",
    slug: "budget-friendly-makeovers-dhaka",
    excerpt:
      "A stunning home transformation doesn't require crores. We share real stories of Dhaka families who achieved magazine-worthy interiors with strategic investments. Paint, lighting, and clever accessorizing can do wonders when guided by experienced designers who understand Bangladeshi budgets.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800&q=80",
    category: "Budget-Friendly Makeovers",
    publishedDate: "2026-08-25",
    author: "Banglasketch Team",
    readingTime: 6,
    featured: false,
    instagramCaption: "Beautiful homes, honest budgets 💰 Dhaka's best transformations under 5 lakh.",
    metaDescription:
      "Budget interior design makeovers in Dhaka. Transform your home for under BDT 5 lakh with expert design tips and strategic investments.",
  },
  {
    id: "bangladeshi-craftsmanship-modern-homes",
    title: "Celebrating Bangladeshi Craftsmanship: Artisanal Touches in Modern Homes",
    slug: "bangladeshi-craftsmanship-modern-homes",
    excerpt:
      "From Tangail saris framed as art to Nakshi Kantha cushions and Dhakai jamdani wall hangings, discover how to incorporate Bangladesh's rich textile heritage into contemporary interiors. These pieces aren't décor—they're stories of our nation's artistry that make every room unmistakably Bengali.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    category: "Bangladeshi Art/Crafts in Modern Homes",
    publishedDate: "2026-08-20",
    author: "Banglasketch Team",
    readingTime: 8,
    featured: true,
    instagramCaption: "Heritage threads in modern rooms 🧵 Bangladeshi craft meets contemporary living.",
    metaDescription:
      "Incorporate Bangladeshi art and crafts into modern interiors. Design ideas featuring Tangail, Nakshi Kantha, and local artisanal pieces for Dhaka homes.",
  },
  {
    id: "luxury-living-room-transformations-gulshan-banani",
    title: "Luxury Living Room Transformations: Gulshan to Banani",
    slug: "luxury-living-room-transformations-gulshan-banani",
    excerpt:
      "Step inside Dhaka's most prestigious living rooms where Italian marble meets Bengali elegance. This collection of luxury transformations showcases custom furniture, imported lighting, and bespoke details that define premium Bangladeshi living. Because Dhaka deserves world-class interiors.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800&q=80",
    category: "Luxury Living Room Transforms",
    publishedDate: "2026-08-15",
    author: "Banglasketch Team",
    readingTime: 5,
    featured: true,
    instagramCaption: "Where luxury meets Bangladeshi soul ✨ Dhaka's most stunning living rooms reimagined.",
    metaDescription:
      "Luxury living room interior design in Dhaka. Premium transformations for Gulshan, Banani, and Dhaka's most prestigious homes.",
  },
  {
    id: "before-after-dhaka-home-renovations",
    title: "Before & After: Remarkable Dhaka Home Renovations",
    slug: "before-after-dhaka-home-renovations",
    excerpt:
      "Witness the dramatic metamorphoses of Dhaka apartments from dated and cramped to dazzling and spacious. These side-by-side comparisons reveal the magic of professional interior design—where every decision from floor plan to finishing touches creates jaw-dropping transformations.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    category: "Before/After Renovation Stories",
    publishedDate: "2026-08-10",
    author: "Banglasketch Team",
    readingTime: 7,
    featured: true,
    instagramCaption: "The moment Dhaka homes transform ✨ From before to breathtaking.",
    metaDescription:
      "Before and after interior design transformations in Dhaka. See dramatic home renovation reveals from Bangladesh's leading design firm.",
  },
  {
    id: "color-palette-guides-dhaka-interiors",
    title: "Color Palette Guides: Choosing the Perfect Hue for Dhaka Interiors",
    slug: "color-palette-guides-dhaka-interiors",
    excerpt:
      "Navigating colors in Dhaka's unique climate and light requires local expertise. Our guide explores palettes inspired by Bengal monsoons, Dhaka sunsets over Buriganga, and warm terracotta Rajshahi tiles. Find tones that make your home feel both cool and connected to our homeland.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80",
    category: "Color Palette Guides",
    publishedDate: "2026-08-05",
    author: "Banglasketch Team",
    readingTime: 6,
    featured: false,
    instagramCaption: "Colors that feel like home 🎨 Dhaka's light, Bangladesh's soul.",
    metaDescription:
      "Interior color palette guide for Dhaka homes. Expert color advice for Bangladesh's unique climate and light conditions.",
  },
  {
    id: "office-commercial-interiors-dhaka",
    title: "Office & Commercial Interiors: Elevating Dhaka's Business Spaces",
    slug: "office-commercial-interiors-dhaka",
    excerpt:
      "Your workspace speaks volumes about your business. From Dhanmondi's creative agencies to Motijheel's corporate headquarters, discover how thoughtful commercial interiors boost productivity, impress clients, and reflect Bangladesh's emerging business sophistication. Design that works as hard as you do.",
    content: "",
    featuredImage: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
    category: "Office/Commercial Interiors",
    publishedDate: "2026-08-01",
    author: "Banglasketch Team",
    readingTime: 5,
    featured: false,
    instagramCaption: "Workspaces that work 🏢 Dhaka's offices, designed for success.",
    metaDescription:
      "Commercial interior design for Dhaka offices and businesses. Professional workspace design in Dhanmondi, Motijheel, and across Bangladesh.",
  },
];
